# -*- coding: utf-8 -*-
"""CD_Balance_Engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gODtQpnz81ZgKErX01h9UxV5LJOEZH5
"""

# ===================1st Code===============================

# ===================== 1) MOUNT DRIVE =====================
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import os

# ===================== 2) PATHS =====================
INPUT_FOLDER = "/content/drive/MyDrive/Acko Health- Business/FY26/EB Health/Premium Files/202602/additional/Prfiles"
OUTPUT_FILE = "/content/drive/MyDrive/Acko Health- Business/FY26/EB Health/Premium Files/202602/additional/CD Balance/CD_MASTER.xlsx"

all_data = []

# ===================== HELPERS =====================
def extract_mpn(filename):
    parts = filename.replace(".xlsx","").split("-")
    return parts[2] if len(parts)>=3 else None

def extract_client(filename):
    return filename.split("-")[0]

# -------- VAN FROM E8 --------
def extract_van_from_cell(path):
    try:
        xls = pd.ExcelFile(path)

        if "CD Statement" not in xls.sheet_names:
            return None

        df = xls.parse("CD Statement", header=None, nrows=10, usecols="A:E")
        text = str(df.iloc[7,4])   # E8 cell

        if "/" in text:
            return "ACKOG4" + text.split("/")[1].strip()

    except:
        pass

    return None

# -------- Detect CD table automatically --------
def detect_table(path):
    xls = pd.ExcelFile(path)

    for sheet in xls.sheet_names:
        raw = xls.parse(sheet, header=None)

        for i in range(min(15,len(raw))):
            row = raw.iloc[i].astype(str).str.lower()

            if any("balance" in c for c in row) and any("date" in c for c in row):
                return xls.parse(sheet, header=i)

    return None


# ===================== PROCESS FILES =====================
files = [f for f in os.listdir(INPUT_FOLDER) if f.endswith(".xlsx")]
print("Total files detected:", len(files))

for file in files:
    try:
        path = os.path.join(INPUT_FOLDER,file)

        df = detect_table(path)
        if df is None:
            print("Skipped:",file)
            continue

        df.columns = df.columns.astype(str)

        bal_col = [c for c in df.columns if "balance" in c.lower()][0]
        date_col = [c for c in df.columns if "date" in c.lower()][0]

        df = df[df[bal_col].notna()]
        df[date_col] = pd.to_datetime(df[date_col],errors="coerce")

        latest = df.sort_values(date_col,ascending=False).head(1)

        latest["Client"] = extract_client(file)
        latest["MPN"] = extract_mpn(file)
        latest["VAN"] = extract_van_from_cell(path)

        latest = latest.rename(columns={date_col:"Date",bal_col:"Balance"})
        all_data.append(latest[["Client","MPN","VAN","Date","Balance"]])

    except Exception as e:
        print("Error in:",file,"|",e)


# ===================== MERGE MASTER =====================
if len(all_data)==0:
    raise Exception("No valid CD files detected")

master = pd.concat(all_data,ignore_index=True)

# keep latest record per policy
master = master.sort_values("Date",ascending=False).drop_duplicates("MPN")

master.to_excel(OUTPUT_FILE,index=False)

print("\n✅ MASTER CREATED:", OUTPUT_FILE)

# ===================2nd Code===============================


# ===================== 1) MOUNT DRIVE =====================
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import os
from datetime import datetime

# ===================== 2) PATHS =====================
INPUT_FOLDER = "/content/drive/MyDrive/Acko Health- Business/FY26/EB Health/Premium Files/202602/additional/Prfiles"
OUTPUT_FILE = "/content/drive/MyDrive/Acko Health- Business/FY26/EB Health/Premium Files/202602/additional/CD Balance/CD_MASTER.xlsx"
CSV_OUTPUT = OUTPUT_FILE.replace(".xlsx", ".csv")

all_data = []

# ===================== HELPERS =====================

def extract_mpn(filename):
    parts = filename.replace(".xlsx","").split("-")
    return parts[2] if len(parts)>=3 else None


# -------- CLIENT FROM DETAILS!D3 --------
def extract_client_from_excel(xls):
    try:
        if "Details" not in xls.sheet_names:
            return None

        df = xls.parse("Details", header=None, usecols="D", nrows=3)
        return str(df.iloc[2,0]).strip()
    except:
        return None


# -------- VAN FROM CD STATEMENT E8 --------
def extract_van_from_excel(xls):
    try:
        if "CD Statement" not in xls.sheet_names:
            return None

        df = xls.parse("CD Statement", header=None, nrows=10, usecols="A:E")
        text = str(df.iloc[7,4])

        if "/" in text:
            return "ACKOG4" + text.split("/")[1].strip()

    except:
        pass

    return None


# -------- Detect CD table automatically --------
def detect_cd_table(xls):

    for sheet in xls.sheet_names:
        raw = xls.parse(sheet, header=None)

        for i in range(min(15,len(raw))):
            row = raw.iloc[i].astype(str).str.lower()

            if any("balance" in c for c in row) and any("date" in c for c in row):
                return xls.parse(sheet, header=i)

    return None


# ===================== PROCESS FILES =====================
files = [f for f in os.listdir(INPUT_FOLDER) if f.endswith(".xlsx")]
print("Total files detected:", len(files))

for file in files:
    try:
        path = os.path.join(INPUT_FOLDER,file)

        # OPEN EXCEL ONCE (important performance improvement)
        xls = pd.ExcelFile(path)

        # Extract metadata
        client_name = extract_client_from_excel(xls)
        van_number = extract_van_from_excel(xls)
        mpn = extract_mpn(file)

        # Extract CD statement
        df = detect_cd_table(xls)
        if df is None:
            print("Skipped:",file)
            continue

        df.columns = df.columns.astype(str)

        bal_col = [c for c in df.columns if "balance" in c.lower()][0]
        date_col = [c for c in df.columns if "date" in c.lower()][0]

        df = df[df[bal_col].notna()]
        df[date_col] = pd.to_datetime(df[date_col],errors="coerce")

        latest = df.sort_values(date_col,ascending=False).head(1).copy()

        latest["Client"] = client_name
        latest["MPN"] = mpn
        latest["VAN"] = van_number

        latest = latest.rename(columns={date_col:"Date",bal_col:"Balance"})
        all_data.append(latest[["Client","MPN","VAN","Date","Balance"]])

    except Exception as e:
        print("Error in:",file,"|",e)


# ===================== MERGE MASTER =====================
if len(all_data)==0:
    raise Exception("No valid CD files detected")

master = pd.concat(all_data,ignore_index=True)

# keep latest record per policy
master = master.sort_values("Date",ascending=False).drop_duplicates("MPN")

# add refresh timestamp
master["Last_Updated"] = datetime.now().strftime("%d-%b-%Y %I:%M %p")

# ===================== DATA CLEANING =====================

master = master.loc[:, master.columns.notna()]
master = master.dropna(axis=1, how="all")

master = master[["Client","MPN","VAN","Date","Balance","Last_Updated"]]

# convert types (VERY IMPORTANT FOR SHEETS)
master["Date"] = master["Date"].dt.strftime("%Y-%m-%d")
master["Balance"] = pd.to_numeric(master["Balance"], errors="coerce")

# remove line breaks
master = master.replace(r'\n|\r', ' ', regex=True)

# ===================== OUTPUT FILES =====================

# Excel backup
master.to_excel(OUTPUT_FILE, index=False)

# Live CSV for Google Sheet
master.to_csv(
    CSV_OUTPUT,
    index=False,
    encoding="utf-8",
    float_format="%.2f"
)

print("\n✅ EXCEL BACKUP:", OUTPUT_FILE)
print("🌐 LIVE CSV READY FOR GOOGLE SHEET:", CSV_OUTPUT)
print("📡 Sheet will auto-refresh via Apps Script trigger")

# ===================3rd Code===============================


# ===================== 1) MOUNT DRIVE =====================
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import os
from datetime import datetime

# ===================== 2) PATHS =====================
INPUT_FOLDER = "/content/drive/MyDrive/Acko Health- Business/FY26/EB Health/Premium Files/202602/Working"
OUTPUT_FILE = "/content/drive/MyDrive/Acko Health- Business/FY26/EB Health/Premium Files/202602/additional/CD Balance/CD_MASTER.xlsx"
CSV_OUTPUT = OUTPUT_FILE.replace(".xlsx", ".csv")
TRACKER_FILE = OUTPUT_FILE.replace("CD_MASTER.xlsx","CD_TRACKER.parquet")

# ===================== HELPERS =====================

def extract_mpn(filename):
    parts = filename.replace(".xlsx","").split("-")
    return parts[2] if len(parts)>=3 else None

# ---- CLIENT FROM Details!D3 ----
def extract_client_from_excel(xls):
    try:
        df = xls.parse("Details", header=None, usecols="D", nrows=3)
        return str(df.iloc[2,0]).strip()
    except:
        return None

# ---- VAN FROM CD Statement!E8 ----
def extract_van_from_excel(xls):
    try:
        df = xls.parse("CD Statement", header=None, nrows=10, usecols="A:E")
        text = str(df.iloc[7,4])
        if "/" in text:
            return "ACKOG4" + text.split("/")[1].strip()
    except:
        pass
    return None

# ---- Detect CD table ----
def detect_cd_table(xls):
    for sheet in xls.sheet_names:
        raw = xls.parse(sheet, header=None)
        for i in range(min(15,len(raw))):
            row = raw.iloc[i].astype(str).str.lower()
            if any("balance" in c for c in row) and any("date" in c for c in row):
                return xls.parse(sheet, header=i)
    return None


# ===================== LOAD TRACKER =====================
if os.path.exists(TRACKER_FILE):
    tracker = pd.read_parquet(TRACKER_FILE)
else:
    tracker = pd.DataFrame(columns=["File","Modified","Client","MPN","VAN","Date","Balance"])

# ===================== PROCESS FILES =====================
files = [f for f in os.listdir(INPUT_FOLDER) if f.endswith(".xlsx")]
print("Total files detected:", len(files))

new_tracker_rows = []

for file in files:
    try:
        path = os.path.join(INPUT_FOLDER,file)
        modified = os.path.getmtime(path)

        old = tracker[tracker["File"]==file]

        # ---- SKIP UNCHANGED FILE ----
        if not old.empty and float(old["Modified"].iloc[0]) == modified:
            new_tracker_rows.append(old.iloc[0])
            continue

        print("Reading:",file)

        xls = pd.ExcelFile(path)

        client_name = extract_client_from_excel(xls)
        van_number = extract_van_from_excel(xls)
        mpn = extract_mpn(file)

        df = detect_cd_table(xls)
        if df is None:
            continue

        df.columns = df.columns.astype(str)

        bal_col = [c for c in df.columns if "balance" in c.lower()][0]
        date_col = [c for c in df.columns if "date" in c.lower()][0]

        df = df[df[bal_col].notna()]
        df[date_col] = pd.to_datetime(df[date_col],errors="coerce")

        latest = df.sort_values(date_col,ascending=False).head(1)

        new_tracker_rows.append({
            "File":file,
            "Modified":modified,
            "Client":client_name,
            "MPN":mpn,
            "VAN":van_number,
            "Date":latest[date_col].iloc[0],
            "Balance":latest[bal_col].iloc[0]
        })

    except Exception as e:
        print("Error:",file,e)


# ===================== BUILD MASTER =====================
tracker = pd.DataFrame(new_tracker_rows)
tracker.to_parquet(TRACKER_FILE, index=False)

master = tracker.copy()
master = master.sort_values("Date",ascending=False).drop_duplicates("MPN")

master["Last_Updated"] = datetime.now().strftime("%d-%b-%Y %I:%M %p")

# format for sheets
master["Date"] = pd.to_datetime(master["Date"]).dt.strftime("%Y-%m-%d")
master["Balance"] = pd.to_numeric(master["Balance"], errors="coerce")

master = master[["Client","MPN","VAN","Date","Balance","Last_Updated"]]
master = master.replace(r'\n|\r', ' ', regex=True)

# ===================== OUTPUT FILES =====================
master.to_excel(OUTPUT_FILE, index=False)

master.to_csv(
    CSV_OUTPUT,
    index=False,
    encoding="utf-8",
    float_format="%.2f"
)

print("\n✅ MASTER CREATED:", OUTPUT_FILE)
print("🌐 CSV READY:", CSV_OUTPUT)
print("⚡ Incremental refresh active (future runs ultra fast)")

#===================4th Code==============

# ===================== 1) MOUNT DRIVE =====================
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import os
from datetime import datetime

# ===================== 2) PATHS =====================
INPUT_FOLDER = "/content/drive/MyDrive/Acko Health- Business/FY26/EB Health/Premium Files/202602/Working"
OUTPUT_FILE = "/content/drive/MyDrive/Acko Health- Business/FY26/EB Health/Premium Files/202602/additional/CD Balance/CD_MASTER.xlsx"
CSV_OUTPUT = OUTPUT_FILE.replace(".xlsx", ".csv")
TRACKER_FILE = OUTPUT_FILE.replace("CD_MASTER.xlsx","CD_TRACKER.parquet")

# ===================== HELPERS =====================

def extract_mpn(filename):
    parts = filename.replace(".xlsx","").split("-")
    return parts[2] if len(parts)>=3 else None

def extract_client_from_excel(xls):
    try:
        df = xls.parse("Details", header=None, usecols="D", nrows=3)
        return str(df.iloc[2,0]).strip()
    except:
        return None

def extract_van_from_excel(xls):
    try:
        df = xls.parse("CD Statement", header=None, nrows=10, usecols="A:E")
        text = str(df.iloc[7,4])
        if "/" in text:
            return "ACKOG4" + text.split("/")[1].strip()
    except:
        pass
    return None

def detect_cd_table(xls):
    for sheet in xls.sheet_names:
        raw = xls.parse(sheet, header=None)
        for i in range(min(15,len(raw))):
            row = raw.iloc[i].astype(str).str.lower()
            if any("balance" in c for c in row) and any("date" in c for c in row):
                return xls.parse(sheet, header=i)
    return None

# ===================== LOAD TRACKER =====================
if os.path.exists(TRACKER_FILE):
    tracker = pd.read_parquet(TRACKER_FILE)
else:
    tracker = pd.DataFrame(columns=["File","Modified","Client","MPN","VAN","Date","Balance"])

tracker_map = {row["File"]: row for _, row in tracker.iterrows()}

# ===================== PROCESS FILES =====================
files = [f for f in os.listdir(INPUT_FOLDER) if f.endswith(".xlsx")]
print("Total files detected:", len(files))

new_tracker_rows = []

for file in files:
    path = os.path.join(INPUT_FOLDER, file)

    try:
        modified = os.path.getmtime(path)

        # ---------- SKIP UNCHANGED FILE ----------
        if file in tracker_map and float(tracker_map[file]["Modified"]) == modified:
            new_tracker_rows.append(tracker_map[file].to_dict())
            continue

        print("Reading:", file)

        # ---------- OPEN ONLY IF CHANGED ----------
        xls = pd.ExcelFile(path)

        client_name = extract_client_from_excel(xls)
        van_number = extract_van_from_excel(xls)
        mpn = extract_mpn(file)

        df = detect_cd_table(xls)
        if df is None:
            continue

        df.columns = df.columns.astype(str)

        bal_col = [c for c in df.columns if "balance" in c.lower()][0]
        date_col = [c for c in df.columns if "date" in c.lower()][0]

        df = df[df[bal_col].notna()]
        df[date_col] = pd.to_datetime(df[date_col], errors="coerce")

        latest = df.sort_values(date_col, ascending=False).head(1)

        new_tracker_rows.append({
            "File": file,
            "Modified": modified,
            "Client": client_name,
            "MPN": mpn,
            "VAN": van_number,
            "Date": latest[date_col].iloc[0],
            "Balance": latest[bal_col].iloc[0]
        })

    except Exception as e:
        print("Error:", file, e)

# ===================== BUILD MASTER =====================
tracker = pd.DataFrame(new_tracker_rows)
tracker.to_parquet(TRACKER_FILE, index=False)

master = tracker.copy()
master = master.sort_values("Date",ascending=False).drop_duplicates("MPN")

master["Last_Updated"] = datetime.now().strftime("%d-%b-%Y %I:%M %p")

# Format for output
master["Date"] = pd.to_datetime(master["Date"]).dt.strftime("%Y-%m-%d")
master["Balance"] = pd.to_numeric(master["Balance"], errors="coerce")

master = master[["Client","MPN","VAN","Date","Balance","Last_Updated"]]
master = master.replace(r'\n|\r', ' ', regex=True)

# ===================== OUTPUT FILES =====================
master.to_excel(OUTPUT_FILE, index=False)

master.to_csv(
    CSV_OUTPUT,
    index=False,
    encoding="utf-8",
    float_format="%.2f"
)

print("\n✅ MASTER CREATED:", OUTPUT_FILE)
print("🌐 CSV READY:", CSV_OUTPUT)
print("⚡ Incremental refresh active → only modified files processed")

import os
tracker = "/content/drive/MyDrive/Acko Health- Business/FY26/EB Health/Premium Files/202602/additional/CD Balance/CD_TRACKER.parquet"

if os.path.exists(tracker):
    os.remove(tracker)
    print("Old tracker removed")
else:    print("No old tracker found")

# ==========================================================
# CD BALANCE ENGINE — COLAB PRODUCTION SAFE BUILD
# ==========================================================

# ---------- 1. AUTHENTICATION (RUN FIRST ALWAYS) ----------
!rm -rf /root/.config/credentials 2>/dev/null

from google.colab import auth, drive
auth.authenticate_user()
drive.mount('/content/drive', force_remount=True)

import google.auth
from googleapiclient.discovery import build

creds, _ = google.auth.default(scopes=["https://www.googleapis.com/auth/drive"])
drive_service = build("drive", "v3", credentials=creds)


# ---------- 2. IMPORTS ----------
import pandas as pd
import io
from datetime import datetime
from googleapiclient.http import MediaIoBaseUpload, MediaIoBaseDownload


# ---------- 3. CONFIGURATION ----------
INPUT_FOLDER_ID  = "1osUmWdmeIuINxxPWKcJ83uPPY2IIqeJK"
OUTPUT_FOLDER_ID = "1J1ji0kth7l7waG6IMqyUbLMc75stv3Q3"

TRACKER_FILENAME = "CD_TRACKER.parquet"
MASTER_FILENAME  = "CD_MASTER.csv"


# ---------- 4. FILE LIST ----------
def list_all_excel_files(folder_id):
    all_files = []
    page_token = None

    while True:
        response = drive_service.files().list(
            q=f"'{folder_id}' in parents and mimeType='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' and trashed=false",
            fields="nextPageToken, files(id,name,modifiedTime,size)",
            pageSize=1000,
            pageToken=page_token
        ).execute()

        all_files.extend(response.get("files", []))
        page_token = response.get("nextPageToken")

        if not page_token:
            break

    return all_files


# ---------- 5. DOWNLOAD ----------
def download_file(file_id):
    request = drive_service.files().get_media(fileId=file_id)
    fh = io.BytesIO()
    downloader = MediaIoBaseDownload(fh, request)

    done = False
    while not done:
        _, done = downloader.next_chunk()

    fh.seek(0)
    return fh


# ---------- 6. UPLOAD / REPLACE ----------
def upload_or_replace(filename, data_bytes):

    media = MediaIoBaseUpload(io.BytesIO(data_bytes),
                              mimetype='application/octet-stream',
                              resumable=True)

    query = f"name='{filename}' and '{OUTPUT_FOLDER_ID}' in parents and trashed=false"
    res = drive_service.files().list(q=query, fields="files(id)").execute()["files"]

    if res:
        drive_service.files().update(fileId=res[0]["id"], media_body=media).execute()
    else:
        drive_service.files().create(
            body={"name": filename, "parents": [OUTPUT_FOLDER_ID]},
            media_body=media
        ).execute()


# ---------- 7. TRACKER ----------
def load_tracker():

    query = f"name='{TRACKER_FILENAME}' and '{OUTPUT_FOLDER_ID}' in parents and trashed=false"
    res = drive_service.files().list(q=query, fields="files(id)").execute()["files"]

    if not res:
        print("First run — tracker will be created")
        return pd.DataFrame(columns=[
            "FileId","Modified","Size",
            "Client","MPN","VAN",
            "Last_Transaction_Date","Last_Balance"
        ])

    fh = download_file(res[0]["id"])
    return pd.read_parquet(fh)


# ---------- 8. HELPERS ----------
def extract_mpn(filename):
    parts = filename.replace(".xlsx","").split("-")
    return parts[2] if len(parts) >= 3 else None

def extract_client(xls):
    try:
        df = xls.parse("Details", header=None, usecols="D", nrows=3)
        return str(df.iloc[2,0]).strip()
    except:
        return None

def extract_van(xls):
    try:
        df = xls.parse("CD Statement", header=None, nrows=10, usecols="A:E")
        text = str(df.iloc[7,4])
        if "/" in text:
            return "ACKOG4" + text.split("/")[1].strip()
    except:
        return None
    return None

def detect_cd_table(xls):
    for sheet in xls.sheet_names:
        raw = xls.parse(sheet, header=None)
        for i in range(min(15, len(raw))):
            row = raw.iloc[i].astype(str).str.lower()
            if any("balance" in c for c in row) and any("date" in c for c in row):
                return xls.parse(sheet, header=i)
    return None


# ---------- 9. PROCESS ----------
files = list_all_excel_files(INPUT_FOLDER_ID)
print("Files detected:", len(files))

tracker = load_tracker()
tracker_dict = tracker.set_index("FileId").to_dict("index") if not tracker.empty else {}

new_rows = []

for file in files:

    fid = file["id"]
    name = file["name"]
    modified = file["modifiedTime"]
    size = file.get("size", None)

    if fid in tracker_dict:
        if tracker_dict[fid]["Modified"] == modified and tracker_dict[fid]["Size"] == size:
            new_rows.append(tracker_dict[fid])
            continue

    print("Reading:", name)

    fh = download_file(fid)
    xls = pd.ExcelFile(fh)

    df = detect_cd_table(xls)
    if df is None:
        continue

    bal_col = [c for c in df.columns if "balance" in str(c).lower()][0]
    date_col = [c for c in df.columns if "date" in str(c).lower()][0]

    df = df[df[bal_col].notna()]
    df[date_col] = pd.to_datetime(df[date_col], errors="coerce")

    latest = df.sort_values(date_col, ascending=False).iloc[0]

    new_rows.append({
        "FileId": fid,
        "Modified": modified,
        "Size": size,
        "Client": extract_client(xls),
        "MPN": extract_mpn(name),
        "VAN": extract_van(xls),
        "Last_Transaction_Date": latest[date_col],
        "Last_Balance": latest[bal_col]
    })


# ---------- 10. MASTER ----------
combined = pd.DataFrame(new_rows)

master = combined.sort_values("Last_Transaction_Date", ascending=False)\
                 .drop_duplicates("MPN")

master["Last_Updated"] = datetime.now().strftime("%d-%b-%Y %I:%M %p")

master["Last_Transaction_Date"] = pd.to_datetime(
    master["Last_Transaction_Date"]
).dt.strftime("%Y-%m-%d")

master["Last_Balance"] = pd.to_numeric(master["Last_Balance"], errors="coerce")

master = master[
    ["Client","MPN","VAN","Last_Transaction_Date","Last_Balance","Last_Updated"]
]


# ---------- 11. SAVE ----------
upload_or_replace(MASTER_FILENAME, master.to_csv(index=False).encode("utf-8"))
upload_or_replace(TRACKER_FILENAME, combined.to_parquet(index=False))

print("\nSUCCESS — Incremental engine ready 🚀")
print("Next runs process only changed files.")